version: "3.7"

services:
  postgres:
    image: "postgres:10"
    container_name: "lemon-extract-postgres"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - ./.data:/var/lib/postgresql/data%
